# Generated by Django 4.2.29 on 2026-04-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Kitchen'), ('preparing', 'Preparing'), ('served', 'Served'), ('paid', 'Paid')], default='draft', max_length=15),
        ),
    ]
