# Generated by Django 4.2.29 on 2026-04-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_self_order_token_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('jain', 'Jain')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
