# Generated by Django 4.2.29 on 2026-04-04 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfOrderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_order_tokens', to='floors.table')),
            ],
            options={
                'db_table': 'self_order_tokens',
            },
        ),
    ]
