# Generated by Django 4.2.29 on 2026-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
    ]
