# Generated by Django 4.2.29 on 2026-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('kitchen', 'Kitchen'), ('cashier', 'Cashier')], default='staff', max_length=10),
        ),
    ]
